.gitignore
src/datasources/tag/README.md
src/datasources/tag/TagDataSource.ts
src/datasources/tag/components/TagQueryEditor.tsx
src/datasources/tag/img/logo-ni.svg
src/datasources/tag/module.ts
src/datasources/tag/plugin.json
src/datasources/tag/types.ts

all the boiler plate for the tag DS.

chore: generate tag data source

---

.config/webpack/utils.ts
.config/webpack/webpack.config.ts
package-lock.json
package.json

- Pulls in latest changes to the configuration generated by [@grafana/create-plugin](https://github.com/grafana/plugin-tools/releases/tag/%40grafana%2Fcreate-plugin%401.11.0)
- Ran `npx @grafana/create-plugin@latest update`
- Verified that plugin build still works as expected

build: @grafana/plugins-tools@1.11.0 update

---

src/datasources/tag/TagDataSource.test.ts
src/datasources/tag/TagDataSource.ts
src/datasources/tag/types.ts

https://dev.azure.com/ni/DevCentral/_workitems/edit/2523337
- Apply `TagDataSource.convertTagValue()` to current value results
- Added auto test covering all tag types

fix(tag): convert strings to numbers for tag current value

---

src/datasources/system/SystemDataSource.test.ts
src/datasources/system/SystemDataSource.ts
src/datasources/system/components/SystemQueryEditor.test.tsx
src/datasources/system/components/SystemQueryEditor.tsx
src/datasources/system/types.ts
src/test/fixtures.ts

- Adds unit tests for previously untested features
- Wrote unit tests for the UI and the data source itself
- Updated fixtures to better match how Grafana renders a plugin's query editor
n/a

test(system): add unit tests

---

src/datasources/system/components/SystemQueryEditor.tsx
src/datasources/system/query_help.md

https://dev.azure.com/ni/DevCentral/_workitems/edit/2485888
- Added `query_help.md`
- Improved field tooltips
n/a

fix(system): improve query help docs

---

src/datasources/tag/TagDataSource.test.ts
src/datasources/tag/TagDataSource.ts
src/datasources/tag/__snapshots__/TagDataSource.test.ts.snap

Need to visualize current value of multiple tags
Made little changes to handle multiple tags
Changed snapshots because structure of returned data is changed

feat(tag): visualizing current value of multiple tags

---

src/datasources/asset-calibration/__snapshots__/AssetCalibrationDataSource.test.ts.snap
src/datasources/asset-calibration/types.ts

In order to comply with the standard Enum formats for SystemLink, an adjustment to the descriptor values is necessary
Adjusted values and tests to comply with the standard format.
Unit testing

refactor(asset): change enum values for calibration forecast descriptors

---

src/datasources/notebook/datasource.ts
src/datasources/notebook/types.ts

Bug [[NotebookPlugin] A generic error is exposed in UI](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2884840)
Added exception, errorCode on the execution

fix(notebook): More specific error in query inspector

---

src/datasources/asset-calibration/AssetCalibrationDataSource.test.ts
src/datasources/asset-calibration/AssetCalibrationDataSource.ts
src/datasources/asset-calibration/__snapshots__/AssetCalibrationDataSource.test.ts.snap
src/datasources/asset-calibration/components/AssetCalibrationQueryEditor.tsx
src/datasources/asset-calibration/types.ts

[User Story 2883034](https://ni.visualstudio.com/DevCentral/_workitems/edit/2883034): [Grafana][BE][UI] Add new field support for Grafana
Added the necessary type and mapping, also updated how workspaces are sent to the query builder.
Added tests for the added grouping.

feat(asset-calibration): workspace grouping

---

src/datasources/asset-calibration/AssetCalibrationDataSource.test.ts
src/datasources/asset-calibration/AssetCalibrationDataSource.ts

[User Story 2798210](https://dev.azure.com/ni/DevCentral/_workitems/edit/2798210): [UI][Grafana] Add support for filters on the Grafana plugin
[Task 2902257](https://dev.azure.com/ni/DevCentral/_workitems/edit/2902257): Support multiselect global variables in query builder
Updated transform functions to take into consideration multi select values.
Updated renew cache mechanism for dependencies.

feat(asset): multiple values from global vals filter support

---

src/core/DataSourceBase.ts
src/datasources/asset-calibration/AssetCalibrationDataSource.test.ts
src/datasources/asset-calibration/AssetCalibrationDataSource.ts
src/datasources/asset/AssetDataSource.test.ts
src/datasources/tag/TagDataSource.test.ts
src/datasources/workspace/WorkspaceDataSource.test.ts

Task: [Don't throw [object Object] if request failed](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2905424)
Check if the error is fetch error, and format the error

feat(asset): fix [object Object] error message

---

src/datasources/asset/AssetDataSource.test.ts
src/datasources/asset/components/AssetQueryEditor.test.ts
src/datasources/asset/components/editors/AssetDataSourceBase.ts
src/datasources/asset/components/editors/list-assets/ListAssetsDataSource.ts
src/datasources/asset/components/editors/list-assets/ListAssetsEditor.test.tsx
src/datasources/asset/components/editors/list-assets/ListAssetsEditor.tsx
src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.test.tsx
src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.tsx
src/datasources/asset/defaults.ts
src/datasources/asset/types/ListAssets.types.ts

Task: [Add basic query builder: with workspace](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2892128)
Added query builder for list assets
Modified & added tests+

feat(asset): query builder for list assets

---

src/datasources/asset/components/editors/asset-summary/AssetSummaryEditor.test.tsx
src/datasources/asset/components/editors/calibration-forecast/query-builder/CalibrationForecastQueryBuilder.tsx
src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.test.tsx
src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.tsx
src/datasources/asset/constants/AssetSummaryQuery.constants.ts
src/datasources/asset/constants/CalibrationForecastQuery.constants.ts
src/datasources/asset/constants/ListAssets.constants.ts
src/datasources/asset/constants/constants.ts
src/datasources/asset/data-sources/AssetDataSourceBase.ts
src/datasources/asset/data-sources/asset-summary/AssetSummaryDataSource.ts
src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.test.ts
src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.ts
src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.test.ts
src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.ts
src/datasources/asset/types/ListAssets.types.ts

Task: [Make query builder work with grafana variables](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2906394)
Make query builder work with grafana variables
Added tests for list assets data source+

feat(asset): add support for grafana variables for list assets

---

src/datasources/asset/AssetDataSource.test.ts
src/datasources/tag/TagConfigEditor.tsx
src/datasources/tag/TagDataSource.test.ts
src/datasources/tag/TagDataSource.ts
src/datasources/tag/__snapshots__/TagDataSource.test.ts.snap
src/datasources/tag/components/TagQueryEditor.tsx
src/datasources/tag/module.ts
src/datasources/tag/types.ts
src/datasources/tag/utils.test.ts
src/datasources/tag/utils.ts

Usage of variables with selected more than one option in path throw error
Added support of multi value variables

feat(tag): add multi value variable support 

---

src/datasources/asset-common/types.ts
src/datasources/asset/AssetDataSource.test.ts
src/datasources/asset/__snapshots__/AssetDataSource.test.ts.snap
src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.ts

Task: [link](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2892131)
Added a new column 
Modified a test+

feat(asset): add calibration due date column

---

src/datasources/asset/AssetDataSource.test.ts
src/datasources/asset/__snapshots__/AssetDataSource.test.ts.snap
src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.ts

Task: [link](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2909685)
Added a new column: location
Modified a test+

feat(asset): add location column to list assets

---

.github/CODEOWNERS

I am leaving NI and will no longer be a code owner.
n/a
n/a

chore: remove @mure as code owner

---

.github/CODEOWNERS

- Ownership has moved
- Product teams should own their own datasources
Update CODEOWNERS
N/A

chore: Update core and datasource codeowners

---

src/datasources/products/components/ProductsQueryEditor.tsx
src/datasources/products/components/ProductsVariableQueryEditor.tsx
src/datasources/products/query_help.md

This pull request includes changes to improve the help doc with more information and UI by updating tooltips for clarity.
* Updated tooltips to provide clearer descriptions of the fields used for querying products.
* Added tooltip to the query By field in the variable query Editor
* Enhanced the query help documentation by adding key features, example queries, and additional resources to help users better understand and utilize the SystemLink Products data source.
- Manually Verified the changes

fix(products): Enhance tooltips and documentation

---

src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx

Feature : [Feature 2605755 ](https://dev.azure.com/ni/DevCentral/_workitems/edit/2605755): Grafana support for results datasource
As part of [Add Results Query editors to the Results Datasource](https://dev.azure.com/ni/DevCentral/_workitems/edit/2980051) user story, this PR has the changes to the tooltip on the controls in the Results Query editor.
- Updated tooltips description for result query editor. 

refactor(results): Tooltips for results query editor

---

.github/CODEOWNERS

To add codeowners for workorders and testplans datasource
Added codeowners
NA

chore: add codeowners for workorders and testplans datasource

---

.github/CODEOWNERS

To update codeowners for workorders and testplans datasource
Added usha as code owner
NA

chore: update codeowners for workorders and testplans datasource 

---

src/core/components/SlQueryBuilder/SlQueryBuilder.css
src/core/components/SlQueryBuilder/SlQueryBuilder.tsx

To fix the styling issues with shared QB
- Added the theme to query builder following [themeBuilder documentation](https://www.htmlelements.com/docs/themebuilder/)
- Removed the addition of`theme` attribute to body
- Fixed the style of operations dropdown

fix(core): Stylings of shared query builder

---

src/datasources/results/ResultsConfigEditor.tsx
src/datasources/results/components/ResultsQueryEditor.tsx
src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
src/datasources/results/components/editors/time-range/TimeRangeControls.tsx
src/datasources/results/components/query-builders/steps-querybuilder-wrapper/StepsQueryBuilderWrapper.tsx
src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.tsx

The control labels should be consistent in sentence case
1. Updated all the labels within results data source to be in sentence case
2. Extracted the UI visible string - labels, placeholders and error messages to a constant similar to tooltips
Manually verified the behavior

feat(results): update labels to sentence case

---

src/datasources/test-plans/constants/TestPlansQueryBuilder.constants.ts
src/datasources/work-orders/constants/WorkOrdersQueryBuilder.constants.ts

Update fieldnames and operators to reflect the SLE counterparts
- Updated supported operations
- Updated field names

fix(testplans, workorders): Update field name and operators

---

src/datasources/test-plans/TestPlansDataSource.test.ts
src/datasources/test-plans/TestPlansDataSource.ts
src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
src/datasources/test-plans/components/TestPlansVariableQueryEditor.test.tsx
src/datasources/test-plans/components/query-builder/TestPlansQueryBuilder.test.tsx
src/datasources/test-plans/types.ts
src/shared/product.utils.test.ts
src/shared/product.utils.ts
src/shared/types/QueryProducts.types.ts

To support more additional fields for test plans data source
- Added `Product name`, `Product ID` and `Part number` for the product related information
- Added `DUT ID` and `DUT name` for the dut related information 
- added and updated unit tests

fix(test-plans): update test plans data source properties

---

README.md
src/datasources/work-orders/query_help.md

To ad help documentation for workorders datasource 
- Created the `query_help.md` file to provide information about the Work Orders datasource, including key features, example queries and additional resources sections.

docs(workorders): add workorders query help

---

src/datasources/results/components/ResultsQueryEditor.test.tsx
src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
src/datasources/results/components/query-builders/steps-querybuilder-wrapper/StepsQueryBuilderWrapper.test.tsx
src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.test.tsx
src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.test.ts

This pull request introduces additional test cases to cover scenarios that were previously missed.
NA
- Added new test cases
- Updated existing ones to improve overall coverage

test(results): Add missing tests and enhance existing coverage

---

src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.ts

This PR contains changes to  verify the [fix](https://github.com/ni/systemlink-grafana-plugins/pull/334) to remove duplicate error toast message in dashboard.
- Copied `fetch` implementation in steps and store url from options separately
- Use the above fetch with `showErrorAlert: false` to remove duplicate toasts
- Manually verified, the current change is not breaking anything. All tests are passing
These changes will be reverted once verified

fix(results): Fix duplicate error toasts in steps

---

src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.ts

This PR contains changes to revert the changes introduced in this [PR](https://github.com/ni/systemlink-grafana-plugins/pull/333) to verify the [fix](https://github.com/ni/systemlink-grafana-plugins/pull/334) to remove duplicate error toast message in dashboard.
- Reverted the changes
- Manually verified and all tests are passing

fix(results): Revert changes to fix duplicate error in steps

---

README.md
provisioning/example.yaml

To add testplans and workorders to readme and and example yaml file
- Update example.yaml
- Update ReadMe
NA

docs: Add testplans and workorders to readme and and example yaml

---

src/datasources/work-orders/WorkOrdersDataSource.ts

Update url of `create-api-session` route
add instanceSettings.url before the endpoint
Manual testing

fix(prototype): Update create-api-session url

---

src/datasources/work-orders/WorkOrdersDataSource.ts

Reverts ni/systemlink-grafana-plugins#384

fix(prototype): Revert use backend server to call the export-url

---

src/datasources/work-orders/WorkOrdersDataSource.test.ts
src/datasources/work-orders/WorkOrdersDataSource.ts

Reverts ni/systemlink-grafana-plugins#383

fix(prototype): Revert call export-data API for taking metrics

---

.github/CODEOWNERS

To add codeowners for the dataframe DataSource
Added @hemkumarrao-ni , @kartheeswaran-ni , @ushakanagaraj-ni  as owners
NA

chore: Add data-frame datasource owner
