- .github/workflows/pr.yml
The webpack build [runs eslint](https://github.com/ni/systemlink-grafana-plugins/blob/main/.config/webpack/webpack.config.ts#L186), but only for .ts and .tsx files. `npm run lint` also checks JS files, so we should add it to our CI workflow steps to have config files such like `release.config.js` also checked.
- Add lint step to worfklow
n/a
> ci: add lint step to pr workflow

- .vscode/launch.json
- .vscode/tasks.json
- README.md
- package.json
VS Code can attach to an instance of Chrome, which allows you to set and debug breakpoints right in the editor. This is a better workflow then having to open the dev tools separately in Chrome.
- Added a "task" that starts up Docker compose and `npm run dev`.
- Added a launch configuration that runs the task and then attaches to a new Chrome window.
Tried a few scenarios:
- Running the debugger and hitting a breakpoint
- Launching when Docker engine isn't running - correctly throws an error
- Running when the Docker compose is already started - restarts if needed
> Add launch configuration for VS Code

- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/data-frame/plugin.json
We want to use the resource name "Data Table" instead of the service name "Data Frame".
Rename data source.
Trivial - PR build will validate.
> fix: Rename Data Table data source

- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/data-frame/plugin.json
Revert DFS data source rename. Grafana isn't very robust to these renames which resulted in two different breakages.
Revert rename.
Trivial change - PR build will validate.
> fix: Revert Data Frame data source rename

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/test/fixtures.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2387168
- Lets users control the tag path using a dashboard variable
- Call into the `TemplateSrv` to interpolate variables
- Updated `setupDataSource` fixture to include a mock `TemplateSrv` and wrote a new test
> feat(tag): add support for tag path as variable

- .config/webpack/webpack.config.ts
- src/datasources/tag/components/TagQueryEditor.tsx
- src/datasources/tag/query_help.md
https://dev.azure.com/ni/DevCentral/_workitems/edit/2485887
Data sources can include a `query_help.md` markdown file to be displayed in the UI. Unfortunately, the webpack configuration extended from the [plugin tools](https://github.com/grafana/plugin-tools) doesn't copy that file in to the dist, so I had to manually change the config. I upstreamed a change here: https://github.com/grafana/plugin-tools/pull/374
- Built the plugins and viewed the rendered markdown
> feat(tag): add query help documentation

- jest-setup.js
- package-lock.json
- package.json
- src/core/DataSourceBase.ts
- src/core/types.ts
- src/core/utils.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/components/TagQueryEditor.test.tsx
- src/datasources/tag/components/TagQueryEditor.tsx
https://dev.azure.com/ni/DevCentral/_workitems/edit/2502935
Users can select a workspace by name instead of id.
- Added a method to `DataSourceBase` to fetch and cache workspaces
- Wrote a custom hook to get workspaces as Select options
Now that the TagQueryEditor component has side effects, I had to slightly refactor the tests to wait for the workspaces to populate. I combined some of the tests into one in the spirit of https://kentcdodds.com/blog/write-fewer-longer-tests.
> feat(tag): add user-friendly workspace dropdown

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
Before this change, the data source would return a data frame with a name property set to the tag's name. The historical/current field was always named 'value':
**name: my.tag**
| time                | value |
|---------------------|-------|
| 2020-01-02 03:04:00 | 45.0  |
| 2020-01-02 03:05:00 | 47.0  |
| 2020-01-02 03:06:00 | 48.0  |
With this change, the 'value' field will take on the tag's name instead:
| time                | my.tag |
|---------------------|-------|
| 2020-01-02 03:04:00 | 45.0  |
| 2020-01-02 03:05:00 | 47.0  |
| 2020-01-02 03:06:00 | 48.0  |
Grafana's documentation doesn't provide any recommendations on which format is preferable, but the new approach makes the explore mode more usable for visualizing multiple tags.
Fixes [this …
> fix(tag)!: use tag name instead of 'value' for field name

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/types.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2508350
This fixes an edge case where someone tries to visualize the current value of a tag that exists but has never been written to.
There isn't a useful workflow in this case, so I just took the simplest possible approach - returning an empty field when there's no current value.
- Added auto test
> fix(tag): crash when visualizing tag with no value

- src/core/DataSourceBase.ts
- src/core/types.ts
- src/core/utils.ts
- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/test/fixtures.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2523281
The tag plugin is likely to get throttled when making a lot of history requests.
There's a few ways to approach this, but retrying failed requests is the easiest to implement, works even if a user has multiple dashboards open, and can be reused across all our plugins.
The strategy I've applied is to retry a maximum of 3 times with an exponential backoff (1, 2, 4 seconds). The actual delay for each request will be randomized to introduce jitter.
Unfortunately, the mild amount of refactoring from this change did force us to have to rewrite all the tests a bit. I also added two new tests for the retry behavior.
> feat(tag): retry requests for 429 error

- src/core/utils.ts
- src/datasources/system/SystemDataSource.ts
- src/datasources/system/components/SystemQueryEditor.tsx
- src/datasources/system/constants.ts
- src/datasources/system/network-utils.ts
- src/datasources/system/types.ts
- Refactor systems data source to use `DataSourceBase` class and other misc clean up.
- `SystemDataSource` now extends from `DataSourceBase` and uses its `getWorkspaces` implementation
- Moved `getWorkspaceName` to shared utility function
- Remove unneeded `InlineFieldRow` component and use `AutoSizeInput` for system name field
- Hide system name field in Summary mode
- Remove unused types and `NetworkUtils` methods
- Manual testing of plugin. Automated tests will be in the next PR.
> refactor(system): clean up systems data source

- src/datasources/system/SystemDataSource.test.ts
- src/datasources/system/SystemDataSource.ts
- src/datasources/system/components/SystemVariableQueryEditor.test.tsx
- src/datasources/system/components/SystemVariableQueryEditor.tsx
- src/datasources/system/module.ts
- src/datasources/system/types.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2493969
- Added a workspace filter to `getSystemMetadata`
- New component `SystemVariableQueryEditor` that lets users select a workspace
- Added auto tests for the datasource and the new component
> feat(system): filter query variable by workspace

- provisioning/example.yaml
- src/datasources/workspace/README.md
- src/datasources/workspace/WorkspaceDataSource.test.ts
- src/datasources/workspace/WorkspaceDataSource.ts
- src/datasources/workspace/components/WorkspaceQueryEditor.tsx
- src/datasources/workspace/img/logo-ni.svg
- src/datasources/workspace/module.ts
- src/datasources/workspace/plugin.json
- src/datasources/workspace/types.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2527387
- `npm run generate`
- Add to provisioning example file
- Fill in README
- Update data source base and test routes
Validated the datasource is available locally
> feat(workspace): Add skeleton workspace data source

- .eslintrc
- package-lock.json
- package.json
- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/notebook/datasource.test.ts
- src/datasources/system/SystemDataSource.test.ts
- src/datasources/system/components/SystemQueryEditor.test.tsx
- src/datasources/system/components/SystemVariableQueryEditor.test.tsx
- src/datasources/tag/components/TagQueryEditor.test.tsx
The `eslint-plugin-jest` provides extra lint rules for Jest test files. This will help us catch issues like accidentally submitting a  focused test. 
- Add the `eslint-plugin-jest` plugin to our eslint config with the recommended set of rules
- Fixed the new lint errors
n/a
> chore: use `eslint-plugin-jest` to lint test code

- src/core/DataSourceBase.ts
- src/datasources/data-frame/DataFrameDataSource.ts
- src/datasources/data-frame/components/DataFrameQueryEditor.tsx
https://dev.azure.com/ni/DevCentral/_workitems/edit/2527389
Show Data Table Workspace name as `description` text is Data Table selection drop-down and move the ID to `title` (hover text). This involved needing to migrate the Data Table data source to extend `DataSourceBase`.
Tests continue to pass.
> feat(data-frame): Data Frame data source displays associated Workspace

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/__snapshots__/TagDataSource.test.ts.snap
- src/datasources/tag/components/TagQueryEditor.test.tsx
- src/datasources/tag/components/TagQueryEditor.tsx
- src/datasources/tag/types.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2504597
Pretty straightforward - `TagQueryEditor` now has an `InlineSwitch` component that lets users toggle whether or not to show properties. In `TagDataSource`, we map the tag's properties to DataFrame fields and conditionally append them to the result. We ignore properties that start with "nitag" because they're used by the historian service and not useful to users. We also now return the tag's last updated timestamp for the "Current" query mode.
I decided to make the leap to using [snapshot testing](https://jestjs.io/docs/snapshot-testing) for some of the tag data source tests. I've been thinking about it for a while, but this change made updating the test assertions tedious enough that I tried it out. It's _really_ nice for testing …
> feat(tag): include properties in query result

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/types.ts
The Tag API recently had a breaking change which changed previously snake_cased fields to be camelCase instead.
https://ni.visualstudio.com/DevCentral/_workitems/edit/2555738
Update the one field we work with that was affected (workspace).
Verified test dashboard now works with this change.
> fix(tag): Update tag fields to camel case

- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/types.ts
The tag service had a breaking change that we fixed in #45, but the service is in a mixed state of deployment. We should support both properties for now.
- Check both properties
n/a, temporary bandaid
> fix(tag): support both `workspace` and `workspace_id` properties

- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/data-frame/DataFrameDataSource.ts
https://ni.visualstudio.com/DevCentral/_workitems/edit/2553637
https://ni.visualstudio.com/DevCentral/_workitems/edit/2553643
- For the boolean column issue, we're now converting the boolean stored in a string to it's proper type before converting to a data frame and transforming the rest of the values.
-  For the "Value" column issue, we're now just simply setting the column display name configuration to the column name.
- Verified fixes locally
- Updated existing test
> fix(data-frame): Boolean and "Value" columns

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/__snapshots__/TagDataSource.test.ts.snap
- src/datasources/tag/types.ts
The tag service had a [breaking change]( https://dev.azure.com/ni/DevCentral/_git/Skyline/commit/b3d9e6c8392b2d6f1b95de3512faf50d91cd410f?refName=refs%2Fheads%2Fmaster) that renamed the `datatype` field to `type`. We should handle both versions of the tag service to avoid any deployment issues.
- Added a separate interface for the legacy field names
- Check both `type` and `datatype`
- Added unit tests for the legacy fields
> fix(tag): support `datatype` and `type` properties

- src/core/DataSourceBase.ts
- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/data-frame/DataFrameDataSource.ts
- src/datasources/data-frame/components/DataFrameQueryEditor.tsx
- src/datasources/data-frame/types.ts
https://dev.azure.com/ni/DevCentral/_workitems/edit/2566752
- Added a new field to the data frame query model, `type`. "Data" is the original behavior of the plugin and "Metadata" is a new mode that returns a table's properties as a data frame with two fields: name and value.
- I did some refactoring while prototyping. The major things were:
- Cleaned up the data conversion logic to not rely on the transform built in to Grafana (it didn't work for booleans and had an awkward API)
- Added logic to the fake routes in the tests to better match what the actual service does. We were returning all of the columns of fake data in every test, which wasn't technically correct.
- Added a unit test for the metadata query
> feat(dataframe): visualize table properties

- src/core/utils.ts
- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/data-frame/DataFrameDataSource.ts
- src/datasources/data-frame/components/DataFrameQueryEditor.tsx
- src/datasources/data-frame/components/DataFrameQueryEditorCommon.tsx
- src/datasources/data-frame/components/DataFrameVariableQueryEditor.test.tsx
- src/datasources/data-frame/components/DataFrameVariableQueryEditor.tsx
- src/datasources/data-frame/module.ts
https://ni.visualstudio.com/DevCentral/_workitems/edit/2566754
- Added variable support to query editor columns field.
- Added variable query editor to data frame data source that displays a table id field. This field also supports variables. Implemented `metricFindQuery` to return the selected tables columns.
- Since the data frame query editor and variable query editor shared the majority of their logic, this was split out to a helper class that is accessed by both.
- Verified functionality locally
- Added new tests and existing tests continue to pass
> feat(dataframe): Column variable support

- src/datasources/data-frame/DataFrameDataSource.test.ts
- src/datasources/data-frame/DataFrameDataSource.ts
The format of the metadata table returned from the data frame plugin is incorrect. It's returning a row for each property, but we want a field for each property:
- Transposed the data frame returned by the metadata query
- Updated the existing tests
> fix(dataframe): switch orientation of metadata frame

- src/datasources/system/components/SystemQueryEditor.tsx
- src/datasources/workspace/components/WorkspaceQueryEditor.tsx
https://ni.visualstudio.com/DevCentral/_workitems/edit/2598196
- Call `useEffect` to force a query on init
- Also fixed a related issue in the Workspace data source
- Verified functionality locally
- Tests and linter pass
> fix(system): Run query on initial load

- .github/workflows/pr.yml
eslint is producing some warnings because of deprecations. We should fix these at some point, but until then it's cluttering up the PR review because of a new GitHub feature that can't be disabled 😐
- Pass the `--quiet` flag to eslint in the PR workflow
- Ran command locally and verified it does what we expect
> chore: don't emit eslint warnings in PR build

- src/datasources/notebook/QueryEditor.tsx
The notebook parameters are not loading when reopening a visualisation from notebook plugin data source.
Steps to produce:
1) Open a Grafana dashboard which uses a python notebook as a datasource for a vizualition
2) Open the configuration for the visualization
3) Open the query
Use queried notebooks instead of notebooks from actual state. This is a problem because in the same function a state was both set and used. Here is a overview of how calls are made:
componentDidMount: setState, getNotebook, getNotebookMetadata (on retrieved notebook)
getNotebook: get notebook from saved state
Only after componentDidMount & getNotebook is finished the state is actually updated. So, because getNotebook actually called componentDidMount, the saved state there is actually the previous saved state, …
> fix(notebook): fix notebook plugin not loading notebook parameters when opening visualization

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/tag/__snapshots__/TagDataSource.test.ts.snap
- src/datasources/tag/components/TagQueryEditor.test.tsx
- src/datasources/tag/components/TagQueryEditor.tsx
- src/datasources/tag/types.ts
The "history" query type currently visualizes data only for the first matched tag. Need to visualize data from all matched tags.
Implemented functions to retrieve tag history in chunks and merge responses into a single dataframe. Since it is impossible to have properties of multiple tags in one dataframe with those historical values, "Properties" option in now available only for query type "Current".
Added a test to check if the history of multiple tags is processed correctly. Added a test to ensure the properties switch button is hidden when the query type is "History".
> feat(tag): visualize history of multiple tags

- src/core/query-builder.utils.test.ts
- src/core/query-builder.utils.ts
- src/datasources/asset-calibration/AssetCalibrationDataSource.ts
- src/datasources/asset-calibration/components/AssetCalibrationQueryBuilder.test.tsx
- src/datasources/asset-calibration/components/AssetCalibrationQueryBuilder.tsx
- src/datasources/asset-calibration/components/AssetCalibrationQueryEditor.scss
- src/datasources/asset-calibration/components/AssetCalibrationQueryEditor.tsx
- src/datasources/asset-calibration/constants.ts
- src/datasources/asset-calibration/types.ts
[User Story 2798210](https://ni.visualstudio.com/DevCentral/_workitems/edit/2798210): [UI][Grafana] Add support for filters on the Grafana plugin
Used fetched systems, passed them to query builder in order to update the location datasource.
Added and adapted unit tests.
The layout has been updated to reflect the requirements.
> feat(asset-calibration): added systems as dropdown values for location

- src/core/DataSourceBase.ts
- src/core/utils.ts
- src/datasources/asset-calibration/AssetCalibrationDataSource.ts
- src/datasources/asset-calibration/components/AssetCalibrationQueryEditor.tsx
- src/datasources/asset/AssetConfigEditor.tsx
- src/datasources/asset/AssetDataSource.test.ts
- src/datasources/asset/AssetDataSource.ts
- src/datasources/asset/components/AssetQueryEditor.test.ts
- src/datasources/asset/components/AssetQueryEditor.tsx
- src/datasources/asset/components/editors/AssetDataSourceBase.ts
- src/datasources/asset/components/editors/asset-summary/AssetSummaryDataSource.ts
- src/datasources/asset/components/editors/calibration-forecast/CalibrationForecastDataSource.ts
- src/datasources/asset/components/editors/list-assets/ListAssetsDataSource.ts
- src/datasources/asset/components/editors/list-assets/ListAssetsEditor.test.tsx
- src/datasources/asset/components/editors/list-assets/ListAssetsEditor.tsx
- src/datasources/asset/defaults.ts
- src/datasources/asset/module.ts
- src/datasources/asset/types/types.ts
- src/datasources/data-frame/DataFrameDataSource.ts
- src/datasources/system/SystemDataSource.ts
- src/datasources/tag/TagDataSource.ts
- src/datasources/workspace/WorkspaceDataSource.ts
- src/test/fixtures.ts
In order to support granular control on the plugins, we need to have a proper feature flag support. 
- Added feature flag configuration options via jsonData for asset plugins.
- Prepared feature flag support for other plugins as well.
- Unit test
- Manual test
> feat(asset): add feature flag support

- src/datasources/asset-calibration/AssetCalibrationDataSource.test.ts
- src/datasources/asset-calibration/AssetCalibrationDataSource.ts
- src/datasources/asset-calibration/__snapshots__/AssetCalibrationDataSource.test.ts.snap
- src/datasources/asset-calibration/types.ts
[Task 2883056](https://dev.azure.com/ni/DevCentral/_workitems/edit/2883056): [Grafana][UI] Add VendorName, BusType and AssetType GroupBy
Updated the enum, added maps for labels, resolved the values.
Added tests for grouping
> feat(asset): add group by vendor, assetType, busType

- src/datasources/asset/components/AssetQueryEditor.tsx
The explorer fails to start when the asset plugin is selected
Avoid getting to render in loop when query type is set on the explorer
Unit tests
> feat(assets): fix explorer rendering for assets plugin

- src/datasources/asset-calibration/constants.ts
- src/datasources/asset-common/types.ts
- src/datasources/asset/components/AssetQueryEditor.test.ts
- src/datasources/asset/components/AssetQueryEditor.tsx
- src/datasources/asset/components/editors/asset-summary/AssetSummaryDataSource.ts
- src/datasources/asset/components/editors/asset-summary/AssetSummaryEditor.test.tsx
- src/datasources/asset/components/editors/asset-summary/AssetSummaryEditor.tsx
- src/datasources/asset/components/editors/calibration-forecast/CalibrationForecastDataSource.ts
- src/datasources/asset/components/editors/list-assets/ListAssetsDataSource.ts
- src/datasources/asset/types/AssetSummaryQuery.types.ts
- src/datasources/asset/types/CalibrationForecastQuery.types.ts
- src/datasources/asset/types/ListAssets.types.ts
US: [User Story 2855720](https://dev.azure.com/ni/DevCentral/_workitems/edit/2855720): [UI][Grafana] Create 'Summary' option as part of the 'SystemLink Asset' Grafana plugin
Added query to /asset-summary. Modified QueryEditor to not initialize the query with ListAssets every time a different visualisation is selected (the change from useState part).
Added unit tests for asset summary part.
Manually tested:
> feat (asset) Add summary option for asset query type

- src/core/query-builder.utils.test.ts
- src/core/query-builder.utils.ts
- src/datasources/asset-calibration/AssetCalibrationDataSource.ts
- src/datasources/asset-calibration/__snapshots__/AssetCalibrationDataSource.test.ts.snap
- src/datasources/asset-calibration/components/AssetCalibrationQueryEditor.tsx
We don't need Cache for our dependencies, storing them in memory once it's enough.
Setting the dependencies in queryEditor wasn't consistent.
Dependencies wouldn't load unless a query was made.
Used Map for easy retrieval of data instead of TTLCache.
Updated how the queryEditor knows when the loading is finished, used rxjs for it in order to make sure we load the data after everything is set.
Dependencies are loading regardless, if a query is ran at the start it will wait for the dependencies to load, no extra loading is done.
Plugin behaves the same.
- [x ] This PR has a title that follows the [commit message format](https://github.com/ni/systemlink-grafana-plugins#commit-message-format).
> feat(asset): load dependencies only once, change ttlcache to map

- src/datasources/asset/components/editors/calibration-forecast/CalibrationForecastEditor.tsx
- src/datasources/asset/components/editors/calibration-forecast/query-builder/CalibrationForecastQueryBuilder.test.tsx
- src/datasources/asset/components/editors/calibration-forecast/query-builder/CalibrationForecastQueryBuilder.tsx
- src/datasources/asset/components/editors/list-assets/ListAssetsEditor.tsx
- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.test.tsx
- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.tsx
- src/datasources/asset/data-sources/AssetDataSourceBase.ts
[Task 2907642](https://dev.azure.com/ni/DevCentral/_workitems/edit/2907642): Add global variable options in dropdown
Defined global var options in asset data source base, passed it to query builder
- [ x] This PR has a title that follows the [commit message format](https://github.com/ni/systemlink-grafana-plugins#commit-message-format).
> feat(asset):  add global variables as options

- src/datasources/asset/components/editors/calibration-forecast/CalibrationForecastEditor.tsx
- src/datasources/asset/components/editors/calibration-forecast/query-builder/CalibrationForecastQueryBuilder.test.tsx
- src/datasources/asset/components/editors/calibration-forecast/query-builder/CalibrationForecastQueryBuilder.tsx
- src/datasources/asset/components/editors/list-assets/ListAssetsEditor.tsx
- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.tsx
- src/datasources/asset/components/variable-editor/AssetVariableQueryEditor.tsx
- src/datasources/asset/data-sources/AssetDataSourceBase.ts
[Task 2908406](https://dev.azure.com/ni/DevCentral/_workitems/edit/2908406): Fix duplicate variable in query builder dropdown for asset type and bus type
Return a new instance instead of modifying the object.
> feat(asset): avoid side effects on field constants

- src/datasources/asset/data-sources/AssetDataSourceBase.ts
- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.test.ts
- src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.test.ts
The query location fails on empty strings when comparing direct values due to preprocessing on the backend. In order to fix this, I will change the expression to use LINQ that's also supported by the API
- Manual testing
- Updated Unit tests
> fix(asset): fix empty string error on Linq filter for assets

- src/datasources/asset/data-sources/AssetDataSourceBase.ts
- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.test.ts
- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.ts
- src/datasources/asset/data-sources/calibration-forecast/__snapshots__/CalibrationForecastDataSource.test.ts.snap
- src/datasources/asset/types/CalibrationForecastQuery.types.ts
We need the ability to add a flag so the service knows that it needs to query only data in the interval.
Updated data links and runQuery method to take into consideration IncludeOnlyDataInTimeRange
Added tests for the flag
> feat(asset): added support for IncludeOnlyDataInTimeRange

- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.test.tsx
- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.tsx
- src/datasources/asset/constants/ListAssets.constants.ts
- src/datasources/asset/types/types.ts
Task: [link](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2914265)
Add a new option, and make current calibration due date options more friendly
Added a test+
> feat(asset): more friendly options for calibration due date and add new option

- src/core/query-builder.utils.test.ts
- src/core/query-builder.utils.ts
- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.test.tsx
- src/datasources/asset/components/editors/list-assets/query-builder/AssetQueryBuilder.tsx
- src/datasources/asset/constants/constants.ts
- src/datasources/asset/data-sources/AssetDataSourceBase.ts
Task: [link](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/ASW%20SystemLink%20Asset%20Mgmt/Features/?workitem=2915649)
Added a hardcoded value: ${__now:date}, similar to other grafana variables. This will allow us to save the dashboard, and on reload new date will be computed.
Added tests+
> feat(asset): compute "Now" in a way that can be saved

- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.test.ts
- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.ts
- src/datasources/asset/data-sources/calibration-forecast/__snapshots__/CalibrationForecastDataSource.test.ts.snap
Data links have different behavior on local environment.
Used config.appUrl from grafana runtime config in order to build the default url.
Updated snapshots
> fix(asset): data link creation on deployed envs

- src/core/utils.test.ts
- src/core/utils.ts
- src/datasources/notebook/QueryBuilder.test.ts
- src/datasources/notebook/QueryBuilder.tsx
Since the query builder is vulnerable to XSS, we need to ensure that the customers are safe using this feature.
Added sanitization to the filter
- Unit testing
- Manual testing
> fix(notebook): fix input sanitization for notebook query builder

- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.test.ts
- src/datasources/asset/data-sources/calibration-forecast/CalibrationForecastDataSource.ts
- src/datasources/asset/data-sources/calibration-forecast/__snapshots__/CalibrationForecastDataSource.test.ts.snap
- Due to a reported issue in the CST time zone, it seems that the calibration forecast dashboard doesn't build the datalinks properly
- The bucket label was also built in local time instead of UTC
- The datalink time building algorithm was adjusted to account for the actual values from the backend when building the links
- The Buckets labels respect the UTC values now
- Unit testing
- Manual testing on different time zones
> fix(asset): calibration forecast timezone issues on datalinks

- src/datasources/asset/AssetDataSource.test.ts
- src/datasources/asset/AssetDataSource.ts
- src/datasources/asset/__snapshots__/AssetDataSource.test.ts.snap
- src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.ts
When there's not asset name in the dropdowns, the row renders an empty string which makes choosing an asset very difficult.
Improving the existing flow to render the asset identifier parameters when the name/alias is empty
Implemented the logic to construct the identifier when the name attribute is missing
- Manual testing
- Unit testing
> fix(assets): updating visualization for the asset display name in global variable

- src/datasources/asset/AssetDataSource.ts
- src/datasources/asset/__snapshots__/AssetDataSource.test.ts.snap
Based on @joshuaprewitt feedback, I've added the identifier on the default asset names as well.
This will enable the customers to search more easily between their assets by any of the following:
Name, Vendor, Model, Serial Number
When constructing the name, I've included additional details (Name, Vendor, Model, Serial Number) in the asset name to make the search more rich
Manual / Unit tests
> fix(assets): addressing feedback for naming the assets

- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/products/query_help.md
This PR contains changes to the label Name from `Records to query` to `Take` and add a Help doc for the datasource.
-  Updated the label "Records to Query" to "Take" for better clarity.
- Added a description of the `SystemLink Products` data source and a link to further information on analyzing and interacting with test results
N/A
> fix(products): Add query help and update label name in the products datasource

- src/datasources/products/components/ProductsQueryEditor.test.ts
- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/products/components/query-builder/ProductsQueryBuilder.tsx
Inorder to fix the query builder rendering issue : 
This pull request includes updates to the `ProductsQueryBuilder.tsx` file to add new stylesheet imports for the `QueryBuilder` component. These changes ensure that the query builder component has the necessary styles applied.
- The PR changes also include adjusting the input field widths, adding a numeric input type the `Order By` and `Take` elements.
- Added imports for various `smart-webcomponents-react` stylesheets to ensure proper styling of the `QueryBuilder` component.
- Adjusted the width of the `orderBy` and `Take` input field to 26.
- Added type of the `Take` input field to 'number'
- Updated test for numeric value in Take input field
- [ x  ] This PR has a title that follows the [commit message …
> fix(products): Fix query builder css rendering and minor UI improvements

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
- src/datasources/products/components/ProductsQueryEditor.test.ts
We need to set default values for `OrderBy` to `UpdatedAt` and `Decending` to `True`.
Updated the default query
Altered the Test cases 
> fix(products): Set defaults for OrderBy and Decending

- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/products/components/ProductsVariableQueryEditor.tsx
- src/datasources/products/components/query-builder/ProductsQueryBuilder.test.tsx
- src/datasources/products/components/query-builder/ProductsQueryBuilder.tsx
- src/datasources/products/constants/ProductsQueryBuilder.constants.ts
Pull Request
With the recent discussions in the [AC change PR](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/899260#1739531352): we will be supporting `familyName` look up in the query builders of both the query editor and the variable query of Products DataSource , 
This Pull Request contains changes to the `ProductsQueryEditor` and the `ProductsQueryBuilder` to include the family Name lookup.
- Added a new state for `familyNames` in the `ProductsQueryEditor` component and updated the `useEffect` hook to load family names from the datasource.
- Added `familyNames` as a prop and created a new `familyField` using `useMemo` to map family names. 
- Updated the fields array to include `familyField` and removed the static `FAMILY` field from `ProductsQueryBuilderStaticFields`.
- …
> feat(products): Add Family name lookup into the query builder 

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
- src/datasources/products/__snapshots__/ProductsDataSource.test.ts.snap
As per the [ AC change discussion](https://dev.azure.com/ni/DevCentral/_git/Skyline/pullRequest/899260#1739530845), the  variable output format needs to be changed from `Part Number(Family)` to `Product Name( Part Number`
This pull request includes changes to the products data source variable output as requested. 
- Refactored the `metricFindQuery` method to use `name` instead of `family` and adjusted the return mapping to reflect this change.
- Updated the test associated with the `metricFindQuery`
> fix(products): Change the variable query output format

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
As part of fixing the [Bug 3025909](https://dev.azure.com/ni/DevCentral/_workitems/edit/3025909): Products data source - Workspace name should be displayed and not just the workspace UUID, This PR contains the conversion of the workspace Id to workspace names.
- Refactored the conditioning using a switch case 
- Used the `getWorkspaceName` method from the Utils to convert the workspace Id to Workspace name
- Added Test case to check the workspace name to be displayed 
> fix(products): Add workspace id to name conversion in query response

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
As part of [Bug 3025905](https://dev.azure.com/ni/DevCentral/_workitems/edit/3025905): Products data source query builder doesn't support multi value variables, This PR contains the fix to support multiple values in the variable query builder
- Added logic to transform the queryBy with multiple values into the expected format
- Added tests to check if multi value is supported
> fix(products): Enhance metricFindQuery to support multiple values

- src/datasources/products/components/ProductsQueryEditor.test.ts
- src/datasources/products/components/ProductsQueryEditor.tsx
On testing the Products Datasource on different browsers, we noticed that the `autoSizeInput` element with Number type used for `Take` field which should allow only Numbers, works properly in `Edge` but allows Alphabets and symbols in `Firefox` and `Chrome` . 
This PR has the changes to enhance input validation for the Take field in all browsers.
-   Added a `checkIfNumber` function to ensure that only numeric values or specific control keys (Backspace, Tab, Delete, ArrowLeft, ArrowRight) are allowed in the record count input field.
- Integrated the `checkIfNumber` function with the `onKeyDown` event of the record count input field to enforce the validation.
Tested manually in all browsers
Added unit tests to verify the same
- [ x ] This PR has a title that follows the [commit message …
> fix(products): Prevent non-numeric input in record count field

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
In order to solve : [Bug 3034280](https://dev.azure.com/ni/DevCentral/_workitems/edit/3034280): Grafana Product data source | Filters are not grouped together if a variable with multi value is used in the query builder, 
We need to enclose the filter within parenthesis for grouping of queries
- Added additional parentheses to MultiValueQuery forming logic
- Updated the existing test cases
- [  x ] This PR has a title that follows the [commit message format](https://github.com/ni/systemlink-grafana-plugins#commit-message-format).
> fix(products): Enclose filter conditions in parentheses for grouping

- src/datasources/tag/TagConfigEditor.tsx
- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
[User Story 3036390](https://ni.visualstudio.com/DevCentral/_workitems/edit/3036390): [Grafana] Revisit code & enable multiselect values for tags plugin
Removed the features setup as it only contained the multiselect flag. Removed previous logic and defaulted to multiselect, arranged the code, adapted the tests.
Updated unit tests.
> feat(tags) - default to multiselect

- src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
Feature : [Feature 2605755 ](https://dev.azure.com/ni/DevCentral/_workitems/edit/2605755): Grafana support for results datasource
As part of [Add Results Query editors to the Results Datasource](https://dev.azure.com/ni/DevCentral/_workitems/edit/2980051) user story, this PR has the changes to enhance input validation for the Take field in all browsers.[`AutoSizeInput`](vscode-file://vscode-app/c:/Users/aradhakr/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) element with the `number` type, used for the "Take" field (which should only accept numeric input), behaves as expected in Edge but allows alphabets and symbols in Firefox and Chrome. 
- Added `validateNumericInput` function from `Utils` to handle numeric input …
> fix(results): Prevent non-numeric input in record count(Take) field

- src/datasources/results/constants/ResultsQueryBuilder.constants.ts
- src/datasources/results/types/QueryResults.types.ts
As a part of this [User Story 2798322](https://ni.visualstudio.com/DevCentral/_workitems/edit/2798322): FE | Add Query Builder for Results Datasource
this PR introduces constants and types required for implementing the query builder functionality for the Results datasource.
In `ResultsQueryBuilder.constants.ts`: 
- Added `ResultsQueryBuilderFieldNames` to define the field names used in the query builder.
- Added `ResultsQueryBuilderFields` to configure field metadata, including labels, filter operations, and lookup values.
- Added `ResultsQueryBuilderStaticFields` to define static fields for the query builder.
In `QueryResults.types.ts`:
- Added `QBField` type to represent the structure of query builder fields.
- Added `queryBy` property in the `QueryResults` type to support query …
> feat(results): Add Constants for Results Query Builder

- src/core/utils.test.ts
- src/core/utils.ts
- src/datasources/data-frame/DataFrameDataSource.test.ts
To fix : [Bug 3107967](https://dev.azure.com/ni/DevCentral/_workitems/edit/3107967): Dataframe data source doesn't handle Grafana variables when 'All' is selected as an option from the variable dropdown
We need to refactor the `replaceVariables` method to properly handle the `All` selection in the variables, as the `variable.current.value` of the `All` selection of variables is `$__all`, which is currently causing failures : 
- Refactored the logic of replacing the variables using `templateSrv.replace` instead of `template.Srv.getVariables` which does not list the proper value under `$__all` variable.
- Removed curly braces from multi-value variables as they return strings enclosed within curly braces
- Added unit test cases.
- Manually verified in Local env
- [ x ] This PR has a title …
> fix(data-frame): Replace Variable support for $__all variable

- src/datasources/results/ResultsConfigEditor.test.tsx
- src/datasources/results/ResultsConfigEditor.tsx
- src/datasources/results/ResultsDataSource.ts
- src/datasources/results/components/ResultsQueryEditor.test.tsx
- src/datasources/results/components/ResultsQueryEditor.tsx
- src/datasources/results/module.ts
- src/datasources/results/types/types.ts
As a part of the [User Story 2798322](https://ni.visualstudio.com/DevCentral/_workitems/edit/2798322): FE | Add Query Builder for Results Datasource
this PR introduces the ResultsConfigEditor to  toggle feature flags `queryByResults` and `queryBySteps`, enabling or disabling the visibility of the respective query builders.
- Added `ResultsConfigEditor` to having `DatasourceHttpSettings` and toggle switches to control the visibility of the Results and Steps Query Builders based on feature flags.
- Updated `module.ts` to set `ResultsConfigEditor` using `setConfigEditor` method and `ResultsDataSourceOptions` to define the datasource configuration type 
- Created required interfaces and constant for the feature flag toggles.
- Updated the Results Editor and Datasource to include the …
> feat(results): Introduce feature flag toggles for Results and Steps query builders

- src/datasources/test-plans/README.md
- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/test-plans/img/logo-ni.svg
- src/datasources/test-plans/module.ts
- src/datasources/test-plans/plugin.json
- src/datasources/test-plans/types.ts
[User Story 3108772](https://ni.visualstudio.com/DevCentral/_workitems/edit/3108772): FE | Set base
To set base for Test plans data source
- Generated a new data source test-plans following the [Getting started - Grafana Plugin Development for SLE](https://dev.azure.com/ni/DevCentral/_wiki/wikis/AppCentral.wiki/108813/Getting-started-Grafana-Plugin-Development-for-SLE).
- Removed unnecessary code generated
> feat(testplans): Set base for testplans

- src/core/types.ts
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.tsx
- src/datasources/results/constants/ResultsQueryBuilder.constants.ts
- src/datasources/results/types/QueryResults.types.ts
As a part of [User Story 2798322](https://ni.visualstudio.com/DevCentral/_workitems/edit/2798322): FE | Add Query Builder for Results Datasource,
this PR moves the `QBField` type to `core>types.ts` to make it reusable across multiple datasources.
- `QBField` extends the `QueryBuilderField` type and adds a `lookup` property to support additional metadata, such as `readonly` and `dataSource`.
NA
> refactor(results): Move QBField Type to Core Types for Reusability

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/test-plans/types.ts
[User Story 3064428](https://ni.visualstudio.com/DevCentral/_workitems/edit/3064428): FE | Add Query Editor
To enable toggle for output type to select `Properties` or `Total Count`
- Added Radio selection control in test plans query editor
- Added output type in the test plan query
> feat: add output type to test plans query editor

- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.test.tsx
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.tsx
- src/datasources/results/constants/ResultsQueryBuilder.constants.ts
To address the issue with the Keyword field filter operations, as it represents a list rather than a string, the filter operations have been updated to handle list-based operations instead of string-based ones.
- Updated the filter operations for the Keyword field to handle it as a list instead of a string.
- Added the respective list-based operations to the custom operations array in the query builder.
Yet to add
> fix(results): Update keyword filter operations in result query builder

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/test-plans/types.ts
[User Story 3064428](https://ni.visualstudio.com/DevCentral/_workitems/edit/3064428): FE | Add Query Editor
Added multi select for properties in query editor and added default properties in datasource
> feat: add properties to test plans query editor

- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/query-builders/steps-querybuilder-wrapper/StepsQueryBuilderWrapper.tsx
As part of this [User Story 2798322](https://ni.visualstudio.com/DevCentral/_workitems/edit/2798322): FE | Add Query Builder for Results Datasource
this PR introduces the addition of tooltips for `ResultsQueryBuilder` and `StepsQueryBuilder` to provide concise information of query builder for the users.
- Added tooltip for `ResultsQueryBuilder` in `QueryResultsEditor`.
- Added tooltips for `ResultsQueryBuilder` and `StepsQueryBuilder` in `StepsQueryBuilderWrapper`.
NA
> feat(results): Add tooltip for results and steps query builder

- src/datasources/results/ResultsDataSource.test.ts
- src/datasources/results/ResultsDataSource.ts
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.test.tsx
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.tsx
- src/datasources/results/module.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
- src/datasources/results/types/QueryResults.types.ts
As part of [Task 2962922](https://dev.azure.com/ni/DevCentral/_workitems/edit/2962922): Add query editor for Results variable support, this PR contains the changes for the template of the variable query editor with the query builder and the properties element
- Added a `metricFindQuery` method to `ResultsDataSource` and `QueryResultsDataSource` to handle variable queries.
- Introduced a new interface `ResultsVariableQuery` to extend the existing `ResultsQuery` with `properties` and `queryBy` fields. 
- Created a new React component to allow users to configure variable queries via a user interface
> feat(results): Add variable Query editor template for Results Datasource

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/test-plans/components/TestPlansQueryEditor.scss
- src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/test-plans/types.ts
[User Story 3064428](https://ni.visualstudio.com/DevCentral/_workitems/edit/3064428): FE | Add Query Editor
To add controls OrderBy and Descending
Added controls to select rderBy & Descending toggles in test plan query editor.
> feat: add order by and descending controls in test plans data source

- src/datasources/products/components/ProductsQueryEditor.test.ts
- src/datasources/products/components/ProductsQueryEditor.tsx
To Fix: [Bug 3120762](https://dev.azure.com/ni/DevCentral/_workitems/edit/3120762): Products Datasource | Panel failed to refresh with default values.
- Added an `useEffect` which triggers the `HandleQueryChange` to run on mount .
> fix(products): Render and run Query on Mount

- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.test.tsx
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.tsx
As part of  [User Story 2798323](https://dev.azure.com/ni/DevCentral/_workitems/edit/2798323): FE | Add Variable Query Editor for Results DataSource, this PR contains changes to the queryProps of `ResultsVariableQueryEditor` and adding functionality to load workspaces and part numbers.
- Replaced `QueryResultsDataSource` with `ResultsDataSource` to get the queryResultsDatasource instance and methods like the `getProductNames` and `getWorkspaces` from the base class. 
- Added `useEffect` hooks to load workspaces and part numbers on mount, and updated state management with `useState` and `useRef`. 
- Updated the `tooltips` object for consistency in formatting.
- Added unit test cases to check loading of lookups
> feat(results): Load PartNumber and Workspace lookups in Variable Editor Query builder

- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
As part of [User Story 2798323](https://dev.azure.com/ni/DevCentral/_workitems/edit/2798323): FE | Add Variable Query Editor for Results DataSource. This PR contains changes to the `QueryResultsDatasource` by adding logic to the `metricFindQuery` method. 
- Updated the `metricFindQuery` method to process queries with optional filters, transform computed fields, and handle query results with better type safety.
- Added a private utility method `flattenAndDeduplicate` to simplify and deduplicate arrays of strings or arrays of strings. 
- Added unit test cases
> feat(results): Add logic to metricFindQuery of results variable query

- src/datasources/results/components/ResultsQueryEditor.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
- src/datasources/results/components/editors/time-range/TimeRangeControls.tsx
- src/datasources/results/components/query-builders/steps-querybuilder-wrapper/StepsQueryBuilderWrapper.tsx
As a part of this [User Story 2798322](https://ni.visualstudio.com/DevCentral/_workitems/edit/2798322): FE | Add Query Builder for Results Datasource,
This PR increases the label width from 25 to 26 across all controls. The adjustment was necessary because, in the Results Query Editor for steps, the labels were misaligned, and the text exceeded the available space after adding a tooltip. To ensure consistent alignment and spacing across all controls, the label width has been updated to 26.
- Updated `labelWidth` of all controlsr from `25` to `26`. 
Before
After
NA
> fix(results): Align label widths

- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.test.tsx
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.tsx
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
This PR contains changes to conditionally render the query builder in the Results Variable Query Editor.
- Add a condition to render the "Query by result properties" field only when properties are selected . This ensures the query builder is displayed contextually.
- Add condition to call the API only when the properties are selected.
- Increase the label width for the "Properties" and "Query by result properties" fields from 12 to 25 for better alignment and readability.
- Updated the Unit test cases to check the conditional rendering
> feat(results):  Conditionally render QueryBy field and adjust label widths

- src/core/query-builder.constants.ts
- src/datasources/products/components/query-builder/ProductsQueryBuilder.tsx
- src/datasources/products/constants/ProductsQueryBuilder.constants.ts
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.test.tsx
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.tsx
- src/datasources/results/components/query-builders/query-steps/StepsQueryBuilder.test.tsx
- src/datasources/results/components/query-builders/query-steps/StepsQueryBuilder.tsx
- src/datasources/results/constants/ResultsQueryBuilder.constants.ts
- src/datasources/results/constants/StepsQueryBuilder.constants.ts
As part of  [User Story 3112060](https://dev.azure.com/ni/DevCentral/_workitems/edit/3112060): Refactor | Update date time type filter operators. This pull request replaces older date-time filter operations to `DATE_TIME_IS_AFTER` and `DATE_TIME_IS_BEFORE`, in the query builder. 
-  Added `DATE_TIME_IS_AFTER` and `DATE_TIME_IS_BEFORE` operations to `QueryBuilderOperations` with corresponding labels, names, and expression templates.
- Included these new operations in the `customOperations` array for broader usage.
-  Integrated the new operations into the `ProductsQueryBuilder`, `ResultsQueryBuilder`, and `StepsQueryBuilder` components to support filtering by date-time fields.
- Replaced older numeric-based filter operations (e.g., `GREATER_THAN`, `LESS_THAN`) with `DATE_TIME_IS_AFTER` and …
> feat: Update Date-Time query builder operators to 'isAfter' & 'isBefore'

- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
Aligning to the following [comment ](https://ni.visualstudio.com/DevCentral/_workitems/edit/2605755#9933748)in the feature, we need to align the descending control below the orderBy.
Before : 
After: 
- Removed unnecessary `div` elements with the class `horizontal-control-group` in `ProductsQueryEditor`, `QueryResultsEditor`, and `QueryStepsEditor` to simplify the component structure. 
-  Standardized the `labelWidth` property for `InlineField` components to ensure consistent alignment 
- Manually verified the UI
> fix(products, results): Refactor Descending control below the Order by

- src/datasources/work-orders/components/WorkOrdersQueryEditor.test.tsx
- src/datasources/work-orders/components/WorkOrdersQueryEditor.tsx
To add the functionality to handle query change when query filter changes
- Added function to handle query by change
- Fixed the options of order by
- Called query change on mount
> feat(workorders): add query by change

- src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
This PR ensures that the Order By, Descending, and Take controls are hidden when the output type is set to Total Count and the query type is Steps.
- Added a condition to hide the Order By, Descending, and Take controls only when the output type is Total Count.
- Added unit test
> fix(results): Hide Order by and Take fields when output type is set to total count

- src/core/query-builder.constants.ts
- src/datasources/test-plans/components/TestPlansQueryEditor.scss
- src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/test-plans/components/TestPlansVariableQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansVariableQueryEditor.tsx
- src/datasources/test-plans/components/query-builder/TestPlansQueryBuilder.test.tsx
- src/datasources/test-plans/components/query-builder/TestPlansQueryBuilder.tsx
- src/datasources/test-plans/constants/TestPlansQueryBuilder.constants.ts
- src/datasources/test-plans/types.ts
[Task 3105000](https://ni.visualstudio.com/DevCentral/_workitems/edit/3105000): Add query builder for testplans
To add query builder for test plans data source in query editor & variable query editor
- Created `TestPlansQueryBuilder` - wrapper of `SlQueryBuilder`
- Use them in `TestPlansQueryEditor` and `TestPLansVariableQueryEditor`
- Add supported filters and their operators
- Added `LIST_IS_EMPTY` and `LIST_IS_NOT_EMPTY` in core 
> feat(test-plan): add dummy query builder in test plans editors

- src/datasources/results/ResultsDataSourceBase.ts
- src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/defaultQueries.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
- src/datasources/results/types/QueryResults.types.ts
- src/datasources/results/types/types.ts
As a part of this [User Story 3141634](https://dev.azure.com/ni/DevCentral/_workitems/edit/3141634): FE | Add Product (Part Number) Multi-Select Field,
This PR introduces the product name as a separate field to generate the part number query. The motivation for this change is to ensure that the part number remains a required field in steps query type. For consistency, the same approach is implemented in the results query type by adding a dedicated product field.
For more context, see the[ PR comment ](https://github.com/ni/systemlink-grafana-plugins/pull/220#issuecomment-2912246558)where this was discussed.
- In `ResultsDataSourceBase`
- Added `loadProducts` and `queryProducts` methods to fetch product names and their associated part numbers from the `query-product` API endpoint.
- …
> feat(results): Add product multiselect field in results query editor

- src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
As part of fixing: [Task 3128159](https://dev.azure.com/ni/DevCentral/_workitems/edit/3128159): Duplicate API calls when filter includes workspace and time fields .
This pull request introduces enhancements to the query editors (`QueryResultsEditor` and `QueryStepsEditor`) by ensuring that query changes are only triggered when filters are actually modified.
* Modified `onParameterChange` to update `query.queryBy` only when the value changes, preventing unnecessary updates.
* Updated `onResultsFilterChange` and `onStepsFilterChange` to modify `query.resultsQuery` and `query.stepsQuery` only if the values differ, ensuring efficient updates.
* Added a test to confirm that `queryBy` is not updated when the filter remains unchanged.
* Added tests to verify that `resultsQuery` and `stepsQuery` …
> feat(results): prevent duplicate API call 

- src/datasources/work-orders/WorkOrdersDataSource.test.ts
- src/datasources/work-orders/WorkOrdersDataSource.ts
- src/datasources/work-orders/components/WorkOrdersQueryEditor.test.tsx
- src/datasources/work-orders/components/WorkOrdersQueryEditor.tsx
- src/datasources/work-orders/components/WorkOrdersVariableQueryEditor.test.tsx
- src/datasources/work-orders/components/WorkOrdersVariableQueryEditor.tsx
- src/datasources/work-orders/components/query-builder/WorkOrdersQueryBuilder.test.tsx
- src/datasources/work-orders/components/query-builder/WorkOrdersQueryBuilder.tsx
To add lookup for user related fields and to convert userId in workorders response to username
- Use obj of user utils class to map user id to name
- Pass the list to users to query builder and use it for create lookup
> feat(workorders): Add users lookup and map users in workorders data

- src/datasources/test-plans/components/query-builder/TestPlansQueryBuilder.test.tsx
- src/datasources/test-plans/constants/TestPlansQueryBuilder.constants.ts
To show list of states in the test plan querybuilder
- Added lookup with list of states that test plans API supports
> feat(test-plans): Add state property lookup in the query builder

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
To query the test plans with estimated duration filters
- Transform `estimatedDurationInDays` and `estimatedDurationInHours` to `estimatedDurationInSeconds` in the request body
> fix(test-plans): transform duration filters in the request body

- src/datasources/products/components/ProductsQueryEditor.test.ts
- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
Currently, when we open a panel from dashboard, there are 12x the number of API calls required going in which makes it impossible for us to use this datasource plugins to build dashboards
The current implementation on running `handleQueryChange` on mount with `useEffect(()=> {}, [])`  is the reason of the 12x API calls due to unhandled promises, removed the implementation. This introduces back the problem of having stale data in the visualization panel when users switch between data sources
> Note: Updated the existing results data source not to use projection/take values when the output type is Total Count as it is not necessary, this should reduce the load on the service for such queries
- Updated the existing tests, verified manually
> fix(results,products): multiple API calls when editing panels

- src/datasources/results/components/query-builders/query-steps/StepsQueryBuilder.test.tsx
- src/datasources/results/constants/StepsQueryBuilder.constants.ts
Task link: [Task 3160722](https://dev.azure.com/ni/DevCentral/_workitems/edit/3160722): Add hasChildren Toggle as part of step filter
This PR introduces the "Has children" property to the steps query builder.
- Added the corresponding label, value, filter operations, and a true/false lookup for the "Has children" field in `StepsQueryBuilder.constants.ts`.
- Added test case
> feat(results): Add "has children" property in steps query builder

- src/datasources/results/defaultQueries.ts
It is decided to reduce the default take of steps query builder to 1000 from 10,000
- updated the respective default constant
- Existing tests cover the test since both the component and the tests refer the same constant, verified manually
> fix(results): update default limit of take to 1000

- src/datasources/results/ResultsDataSourceBase.ts
- src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.test.tsx
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.tsx
- src/datasources/results/components/query-builders/steps-querybuilder-wrapper/StepsQueryBuilderWrapper.test.tsx
- src/datasources/results/components/query-builders/steps-querybuilder-wrapper/StepsQueryBuilderWrapper.tsx
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.test.tsx
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.tsx
- src/datasources/results/constants/ResultsQueryBuilder.constants.ts
- src/datasources/results/defaultQueries.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
- src/datasources/results/types/QueryResults.types.ts
This pull request contains changes to replace the previous product-based querying to the query builder part-number-based querying. 
* Added caching (`_partNumbersCache`) and a new method (`getPartNumbers`) to manage and query part numbers using `ResultsPropertiesOptions.PART_NUMBER`.
* Replaced the product name field with part numbers, added state management for part numbers, and updated the query builder to pass part numbers.
*  Added support for part numbers in the query builder by introducing a new field (`partNumberField`) and updating operations.
- Updated tests to validate part number functionality, removed tests related to product names, and added new tests for rendering part numbers and handling empty caches.
- [ x ] This PR has a title that follows the [commit message …
> feat(results): revert partNumber field for results query

- src/datasources/results/constants/ResultsQueryBuilder.constants.ts
This pull request adds support for a new `Result ID` field in the query builder functionality of the `ResultsQueryBuilder.constants.ts` file. 
* Added `RESULT_ID` to the `ResultsQueryBuilderFieldNames` enum to define the field name.
* Added `RESULTID` to the `ResultsQueryBuilderFields` object with its label, data field, and filter operations (`EQUALS` and `DOES_NOT_EQUAL`).
* Included `ResultsQueryBuilderFields.RESULTID` in the `ResultsQueryBuilderStaticFields` array to make it a static field.
Manually verified
> feat(results): add Result ID field to Results Query Builder

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/work-orders/WorkOrdersDataSource.test.ts
- src/datasources/work-orders/WorkOrdersDataSource.ts
To show column names when there is no data and to show outputs from the "Total count" output type as it's refID instead of "Total Count"
- Remove hardcoded value of "Total count" and passed query name
- Remove the check of length on data when returning fields
- Updated unit tests
> fix(workorders,testplans): Show column names when there is no data and show refID in output's column name

- src/datasources/results/components/ResultsQueryEditor.test.tsx
- src/datasources/results/components/ResultsQueryEditor.tsx
In the current implementation, switching the query type clears all data from the previous selection. We need to preserve the query state so that when a user switches back to a previous query type, their earlier input is retained and visible.
* Added two new state variables, `resultsQuery` and `stepsQuery`, using React's `useState` to manage query data for `Results` and `Steps` query types.
* Updated the `handleQueryTypeChange` function to use the newly introduced state variables (`resultsQuery` and `stepsQuery`) for constructing queries when switching between query types. This ensures better separation and management of query-specific data. 
* Added test to verify that the states are preserved.
> fix(results): Persist query changes between query type switches

- src/core/utils.test.ts
- src/core/utils.ts
Currently, when the API calls ignore requesting for `recordCount` and the number of records are fetched are less than the requested take, the API calls continue to happen without any end. This occurs as we are not accounting for the factor that `continuationToken` will be `null` when the number of records requested are served.
- Updated the `queryInBatches` method to account for `continuationToken` to be `null` to exit the recursion.
- Added unit tests to validate the behavior
> fix(core): infinite api calls with `queryInBatch` method

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
- src/datasources/results/ResultsDataSourceBase.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.test.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.ts
Current Implementation of error handling doesn't handle timeout scenarios (HTTP 504 status code) which contains a html page as the error message. This PR handles the 504 - Timeout Error in Products and results datasource.
* Added logic to handle HTTP 504 errors in the `ProductsDataSource` class, providing a specific timeout error message for `queryProducts` and `queryProductValues` API calls. )
* Implemented timeout error handling for value queries in the `ResultsDataSourceBase` class, ensuring descriptive error titles and messages. 
* Incorporated timeout error handling for step-related queries in the `QueryStepsDataSource` class, including `querySteps` and `loadStepPaths` methods.
* Added tests to validate timeout error handling for `query` and `queryValues` methods.
> feat(products, results): handle 504 timeout errors in product and result queries

- src/datasources/results/components/editors/query-results/QueryResultsEditor.test.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.ts
- src/datasources/results/query-handlers/query-results/__snapshots__/QueryResultsDataSource.test.ts.snap
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.test.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.ts
- src/datasources/results/query-handlers/query-steps/__snapshots__/QueryStepsDataSource.test.ts.snap
This pull request  contains changes invalid queries to return empty data and enhance the handling of edge cases, such as exceeding limits or providing invalid input.
*  Updated the `onRecordCountChange` function to call `handleQueryChange` with `recordCount: undefined` when the input is invalid.
*  Added `isQueryValid` to validate queries and return empty data for invalid queries in `runQuery`.
- Updated the Tests and added test to check if Query is valid
> fix(results): Handle invalid queries to return empty data

- src/datasources/work-orders/WorkOrdersDataSource.test.ts
- src/datasources/work-orders/WorkOrdersDataSource.ts
- src/datasources/work-orders/components/WorkOrdersQueryEditor.test.tsx
- src/datasources/work-orders/components/WorkOrdersQueryEditor.tsx
- src/datasources/work-orders/components/WorkOrdersVariableQueryEditor.test.tsx
- src/datasources/work-orders/components/WorkOrdersVariableQueryEditor.tsx
To show floating errors and warnings when API call fails in workorders datasource
- Added floating error in editors
- Added methods to catch and parse errors in datasource
> feat(workorders): Error handling of workorders

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/work-orders/WorkOrdersDataSource.test.ts
- src/datasources/work-orders/WorkOrdersDataSource.ts
To remove field type from datasource so that all fields are returned as string type. IF necessary user can add transformation to get desired date time format
- Removed field type when processing data
> fix(workorders,testplans): Return field type as string for all fields from datasource

- src/datasources/results/components/ResultsQueryEditor.test.tsx
- src/datasources/results/components/ResultsQueryEditor.tsx
- src/datasources/results/defaultQueries.ts
- src/datasources/results/types/types.ts
The current implementation does not call run Query when switched from other datasource.
This pull request introduces changes to the `ResultsQueryEditor` component by adding default handling for `queryType`, modifying the `ResultsQuery` type to make `queryType` optional, and ensuring `onRunQuery` is called during initialization.
* Introduced a `useEffect` to assign a default `queryType` if none is provided. 
* Made the `queryType` property in the `ResultsQuery` interface optional to account for cases where it is not explicitly set.
* Removed the default `queryType` from `defaultResultsQuery` to allow for dynamic assignment during initialization.
* Added a test to verify that `onRunQuery` is called during initialization and that the `onChange` callback is invoked with the correct query …
> fix(results): run query on initialization when switching datasources

- src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.test.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.ts
The current implementation does not update the dependency when initializing.
This pull request refines the logic for detecting and handling changes in `resultsQuery`.
* Simplified the `loadStepPaths` method in `QueryStepsDataSource` by removing unused parameters and streamlining its implementation. (
* Consolidated duplicate logic for updating `stepsPath` into the new `validateAndUpdateStepPaths` method, reducing redundancy across the codebase.
* Refined the logic in `onResultsFilterChange` within `QueryStepsEditor` to ensure that `handleQueryChange` is triggered only when `resultsQuery` differs from both the current and previous values.
* Updated `QueryStepsDataSource` to introduce `currentResultsQuery` alongside `previousResultsQuery`, and moved the logic for updating `stepsPath` into a …
> feat(results): Update dependencies to load on initialization

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/test-plans/components/TestPlansQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/test-plans/components/TestPlansVariableQueryEditor.test.tsx
- src/datasources/test-plans/components/TestPlansVariableQueryEditor.tsx
To return empty data when user enters invalid queries and to show error message when all properties are removed
- Handled invalidity when all properties are removed
- Check validity of take and properties and return empty data if it's invalid
- Use `prepareQuery` in `metricFindQuery` so that initial run query gets populated with default query
> fix(testplans): Handle invalid queries to return empty data

- src/datasources/results/components/editors/query-steps/QueryStepsEditor.test.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
The current implementation runs into an issue when a valid results query is added and then removed — the results filter can't be cleared properly because an empty results query doesn't render as expected.
To address this, the pull request updates the QueryStepsEditor component to gracefully handle cases where the results query is empty, ensuring proper rendering and cleanup of filters.
* Updated the `onResultsFilterChange` function to explicitly handle cases where the `resultsQuery` is empty, ensuring the `handleQueryChange` function is called with the correct query.
* Added a new test case to verify that the `resultsQuery` is updated correctly when it is set to an empty string.
> fix(results): allow empty results query to trigger update

- src/datasources/results/components/ResultsQueryEditor.test.tsx
- src/datasources/results/components/ResultsQueryEditor.tsx
To fix the behavior of propagating Results query into Steps on rendering ,this pull request preserves steps query state only when switching between query types. 
* Updated the `handleQueryTypeChange` method in `ResultsQueryEditor` to preserve the current `stepsQuery` state when switching from "Steps" to "Results".
* Added a test to ensure that `stepsQuery` values are preserved when switching from "Steps" to "Results" and back to "Steps". This verifies that custom fields in the `stepsQuery` state are retained.
* Added a test to confirm that a default `stepsQuery` is applied when switching from "Results" to "Steps" without a prior `stepsQuery` state.
> fix(results): preserve stepsQuery only when switching query types

- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.test.tsx
- src/datasources/results/components/variable-editors/ResultsVariableQueryEditor.tsx
To fix the Steps query enabled by default in the Results Variable query editor , this PR contains changes to the logic to disable the steps query if the results query is undefined.
* Updated the `disableStepsQueryBuilder` logic to disable the steps query builder when `queryByResults` is either an empty string or `undefined`.
* **Typo correction in `onResultsQueryChange`**: Fixed a typo in the `onResultsQueryChange` function where `queryResultsquery` was incorrectly used instead of `stepsVariableQuery`. 
* Added a test to verify that the steps query builder is disabled when `queryByResults` is `undefined`.
> fix(results): fix steps query not disabled by default in variable editor

- src/core/utils.test.ts
- src/core/utils.ts
To rethrow error in queryUsingSkip as it is handled in TestPlansDatasource
- Rethrow error in `queryUsingSkip`
- Updated tests
> fix(core): Rethow error in queryUsingSkip

- src/core/utils.test.ts
- src/core/utils.ts
In the current implementation, variables created using a datasource are not listed when configuring queries for that same datasource. This happens because those variables are explicitly filtered out if they were created under the same datasource.
[See teams discussion](https://teams.microsoft.com/l/message/19:b0c2c359cadf418ca24bb9a51a67dcea@thread.tacv2/1750350630751?tenantId=eb06985d-06ca-4a17-81da-629ab99f6505&groupId=1e74afef-f47b-4137-ad1b-e550ec9c6bef&parentMessageId=1750350630751&teamName=TM-SystemLink&channelName=Grafana%20Discussions&createdTime=1750350630751).
- Removed the filter from the `getVariableOptions` method
- Added tests to check if all the variables are returned
> fix(core): remove filtering of variable with datasource

- src/datasources/results/constants/QuerySteps.constants.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.test.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.ts
- src/datasources/results/types/QuerySteps.types.ts
The current maximum take per request is 500 considering the response limits from web server when there are more measurements and conditions within a step. This takes too much time for fetching steps as the take is too small.
- Updated the implementation to extend the take from 500 to 1000 when the first step has <25 measurements
- Updated the existing tests and added new unit tests to verify the behavior
- The current implementation of creating the arrays within tests were time consuming and caused intermittent test failures, updated the test setup to create mock step/path arrays before the tests
- Verified the behavior across different use cases manually
> feat(results): extend the take from 500 to 1000 when number of measurements < 25

- src/datasources/results/components/ResultsQueryEditor.test.tsx
- src/datasources/results/components/ResultsQueryEditor.tsx
In the current implementation, the Results datasource in Explore mode was throwing an error and couldn’t be used. To fix this, the query needs to be passed as an additional parameter into the handleQueryChange function.
* Removed the `datasource.prepareQuery` call from the `ResultsQueryEditor` component, simplifying the query initialization process.
* Updated query merging logic to prioritize existing `query` properties over defaults when switching query types, ensuring more predictable behavior
* Added a test to verify that `onChange` is called with `defaultResultsQuery` and `queryType: Results` when `queryType` is undefined.
> fix(results): fix ResultsQueryEditor to handle undefined queryType in Explore mode

- src/datasources/results/query-handlers/query-results/QueryResultsDataSource.test.ts
- src/datasources/results/query-handlers/query-steps/QueryStepsDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/work-orders/WorkOrdersDataSource.test.ts
This PR addresses the issue with the test for the 429 Too Many Requests workflow, which previously resulted in a timeout due to the internal retry logic triggered by a 429 error. Instead of mocking the API to return a 429 error, the test now mocks the post method (used in queryResults) to throw a 429 error directly and verifying that error message is set in the alert
NA
- Updated the test cases for 429 errors to use the new mocking approach.
> test(results,workorders,testplans): Update 429 error handling tests

- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/results/components/editors/query-results/QueryResultsEditor.tsx
- src/datasources/results/components/editors/query-steps/QueryStepsEditor.tsx
- src/datasources/test-plans/components/TestPlansQueryEditor.tsx
- src/datasources/work-orders/components/WorkOrdersQueryEditor.tsx
This PR update modifies the "Properties" dropdown so that its height expands dynamically when new properties are added.
- Removed `maxVisibleValues` and `noMultiWrap` that limited the dropdown’s height from increasing when new properties were added.
Before
After
NA as it is a UI change
> fix(products,results,workorders,testplans): Expand properties dropdown height on adding property

- src/datasources/results/components/query-builders/QueryBuilder.scss
- src/datasources/results/components/query-builders/query-results/ResultsQueryBuilder.tsx
- src/datasources/results/components/query-builders/query-steps/StepsQueryBuilder.tsx
In cases where the dropdown contains a value that's too long to fit within the visible area, users are unable to see the full text. To address this, a horizontal scrollbar should be added to allow users to scroll and view the entire value.
This pull request introduces a custom theme for dropdown menus in query builders, improving both styling and usability—especially when handling longer values in the dropdown options. 
The CSS is adapted from the Dataspace implementation of the query builder that includes a scrollbar : https://dev.azure.com/ni/DevCentral/_git/Skyline?path=/Web/Workspaces/TestInsights/src/app/dataspaces/components/dataspaces-query-builder/dataspaces-query-builder.component.scss
- Added SCSS definitions for the `custom-theme`, including properties for dropdown menu …
> feat(results): add custom theme support for horizontal scrollbar in query-builder

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
- src/datasources/products/__snapshots__/ProductsDataSource.test.ts.snap
- src/datasources/products/components/ProductsQueryEditor.test.ts
- src/datasources/products/components/ProductsQueryEditor.tsx
To improve query handling in the `ProductsDataSource`,  we need to validate invalid query inputs by adding logic for empty or invalid queries.
* Added logic to return empty data when the query has no properties or an undefined `recordCount`. This prevents unnecessary processing of invalid queries.
* Updated snapshot tests to reflect the new behavior for invalid queries, ensuring test coverage for scenarios with empty data.
> feat(products): handle invalid queries in Products Query Editor

- src/datasources/tag/TagDataSource.test.ts
- src/datasources/tag/TagDataSource.ts
The current endpoint that uses LINQ is very slow. We've introduced a new endpoint that should significantly increase the speed of the queries on the tags.
Modified the code to query for tags using the fetch-tags-with-values endpoint.
- Unit tests
- Manul tests
> feat(tags): update tag datasource with new endpoint to fetch tag data

- src/datasources/products/ProductsDataSource.test.ts
- src/datasources/products/ProductsDataSource.ts
- src/datasources/products/__snapshots__/ProductsDataSource.test.ts.snap
- src/datasources/products/components/ProductsQueryEditor.tsx
- src/datasources/products/types.ts
This pull request updates the column headers in the panel to Sentence case and to improve consistency and readability by replacing hardcoded property names with a centralized lookups (`productsProjectionLabelLookup`). 
- Replaced `ProductPropertiesProjectionMap` with `productsProjectionLabelLookup`, which maps `Properties` enum values to their corresponding labels and projections. Updated the `Properties` enum to use lowercase keys for consistency. 
-  Modified the `MultiSelect` component to use `productsProjectionLabelLookup` for generating property options dynamically.
- Updated the tests and snapshots
> feat(products): update field labels and refactor projection mapping 

- src/datasources/test-plans/TestPlansDataSource.test.ts
- src/datasources/test-plans/TestPlansDataSource.ts
- src/datasources/work-orders/WorkOrdersDataSource.test.ts
- src/datasources/work-orders/WorkOrdersDataSource.ts
[Bug 3190329](https://dev.azure.com/ni/DevCentral/_workitems/edit/3190329): Sort variables in OOTB dashboards in alphabetical order
This pull request introduces functionality to sort options (workorders, testplans) alphabetically by their display text across multiple data sources. It also includes corresponding test cases to validate the sorting behavior.
- Updated `WorkOrdersDataSource` and `TestPlansDataSource` to sort options alphabetically by their `text` values before returning them. 
> fix(workorders,testplans): Sort variable options by their label

- .github/CODEOWNERS
- README.md
My last commit updated the Grafana dependencies to the next major version (11.x). This should have been a major version update for `systemlink-grafana-plugins`, but I did not put `BREAKING CHANGE:` in the commit footer as I should have.
This commit updates the README with details about version bumps and forces a new major version to be published.
> docs: Update README and force major release

- src/datasources/products/ProductsDataSource.ts
This PR refactors the `runQuery` method in the products datasource to improve conciseness.
Refer to [this comment](https://github.com/ni/systemlink-grafana-plugins/pull/365#discussion_r2239021627) for the context and origin of this discussion.
- Introduced a private method, `getFieldValues` which takes the products response and a field as parameters to retrieve values for the selected products.
NA
> refactor(products): Refactor run query to make it concise

- src/datasources/asset/AssetDataSource.test.ts
- src/datasources/asset/AssetDataSource.ts
- src/datasources/asset/__snapshots__/AssetDataSource.test.ts.snap
- src/datasources/asset/components/variable-editor/AssetVariableQueryEditor.test.tsx
- src/datasources/asset/components/variable-editor/AssetVariableQueryEditor.tsx
- src/datasources/asset/defaults.ts
- src/datasources/asset/types/AssetVariableQuery.types.ts
This PR adds support for the take parameter in ListAssets data source variable queries, allowing users to limit the number of returned results when defining dashboard variables.
The take value can be configured from the UI, with proper validation to avoid invalid or excessive limits.
A default value is provided via defaultListAssetsVariable.
Query handling:
Added patchListAssetQueryVariable(query) function in AssetDataSource.ts:
1. Merges the provided query with defaultListAssetsVariable to ensure backward compatibility with existing dashboards.
2. Default values: filter: "", take: QUERY_LIMIT (1000)
Integrated patchListAssetsVariableQuery into metricFindQuery for ListAssets variable queries.
Added validation function isTakeValid(take: number | undefined), which is valid if:
1. take is …
> feat(asset):  add take support for query variables for ListAssets data source

- src/core/DataSourceBase.ts
- src/core/utils.test.ts
- src/core/utils.ts
- src/shared/product.utils.ts
- src/shared/system.utils.ts
- src/shared/users.utils.ts
- src/shared/workspace.utils.test.ts
- src/shared/workspace.utils.ts
[Bug 3211809](https://dev.azure.com/ni/DevCentral/_workitems/edit/3211809): Intermittency in the Work Orders and Test Plans data source tests
The `fetch` method is only available on `DataSourceBase` file and cannot be accessed in shared classes. This `fetch` method has error handling and retry logic. This PR holds changes to use common logic for get and post calls, so retry will happen for all APIs
- Moved `fetch` from `DataSourceBase` to `utils`
- Utilize the `fetch` method in all shared utility classes
- Added unit tests and updated existing tests
> fix(shared): use common fetch method for get and post API calls

- src/datasources/asset/AssetDataSource.ts
- src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.ts
- src/datasources/asset/defaults.ts
- src/datasources/asset/types/ListAssets.types.ts
This PR changes the request's body "formattedProjection" element to "projection" and it also updates the Query Asset Variable request body to contain the projection field with a default list of properties.
- in ListAssetsDatasource.ts: changed the request's body "formattedProjection" element to "projection" in queryAssets function
- in ListAssets.types.ts: updated QueryListAssetRequestBody interface to contain "projection" instead of "formattedProjection"
- in defaults.ts: added "defaultProjectionForListAssetsVariable" that contains all the necessary properties for Query Asset Variable
- in AssetDataSource.ts: updated metricFindQuery to call "queryAssets" function with projection set to "defaultProjectionForListAssetsVariable"
Manual testing:
- Verify that:
1. valid values trigger the …
> fix(asset): Update the request body and include projection in Query Assets Variable

- src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.test.ts
- src/datasources/asset/data-sources/list-assets/ListAssetsDataSource.ts
This PR changes the variables with which we are calling queryAssets function, so only one asset with one property is returned and also the total count of assets returned.
In ListAssetsDataSource.ts I've updated processTotalCountAssetsQuery so:
- "response" variable contains a list of assets with only one asset with the id property selected and also the total count of assets returned
- changed "await this.queryAssets(query.filter, QUERY_LIMIT, true, query.properties)" into "await this.queryAssets(query.filter, 1, true, [AssetFilterPropertiesOption.AssetIdentifier])"
- updated "should call queryAsset with returnCount set to true when outpuType is set to TotalCount" test to call the function with take field set to 1 instead of 1000
Manual testing:
- Verify that:
1. when Total Count is …
> perf(asset): Update processTotalCountAssetsQuery so only one asset with one property is returned

- src/datasources/asset/AssetDataSource.test.ts
- src/datasources/asset/AssetDataSource.ts
- src/datasources/asset/components/variable-editor/AssetVariableQueryEditor.test.tsx
- src/datasources/asset/types/types.ts
#3250098
Asset Identification and Asset Id mean the same thing to most users.
Renamed Asset Identification to Asset Tag Path.
> refactor(asset): Rename AssetIdentification to AssetTagPath

- src/datasources/asset/types/ListAssets.types.ts
This PR adds the valid ParentName to "projection".
in ListAssets.types.ts: changed " ParentName = 'ParentName' " into " ParentName = 'Location.Parent' " 
Manual testing:
- Verify that in the query-assets projection, "Location.Parent" appears instead of "ParentName" in the console's payload.
> fix(asset): Update projection for ListAssetsDataSource

- src/core/components/SlQueryBuilder/SlQueryBuilder.test.tsx
- src/core/components/SlQueryBuilder/SlQueryBuilder.tsx
[Bug 3239554](https://dev.azure.com/ni/DevCentral/_workitems/edit/3239554): Grafana | Properties not sorted
Currently the properties in the querybuilder dropdown are not shown in sorted order. Other SLE apps shows the properties in sorted order in the querybuilder. This PR contains changes to sort the fields in the querybuilder.
- Added logic to sort the fields by label.
- Added unit tests for the introduced functionality
> fix(core): sort fields in query builder by label

- src/datasources/alarms/components/query-builder/AlarmsQueryBuilder.test.tsx
- src/datasources/alarms/components/query-builder/AlarmsQueryBuilder.tsx
- src/datasources/alarms/constants/AlarmsQueryBuilder.constants.ts
Add support for filtering by acknowledged on, first occurrence, properties and keywords in alarms query builder
- Added new fields to the query builder: `Acknowledged on`, `First occurrence`, `Keyword`, and `Properties`, each with appropriate filter operations and configuration in `AlarmsQueryBuilderFields` and included in `AlarmsQueryBuilderStaticFields`. 
- Introduced time-based options (`From`, `To`, `Now`) for the `Acknowledged on` and `First occurrence` fields, allowing users to select these as filter values.
- Added additional filter operations for date/time, list, and key/value matching to support the new fields and use cases.
> feat(alarms): support datetime filters, keywords and properties
